### ISSUE TITLE
`superset db upgrade` fails

### ISSUE THREAD

**Issue by lgingerich** [bengen343/superset-on-gcp-cloud-run#3]
Following step 1 of "Build Superset Configuration SQL Database", `superset db upgrade` fails to run with the error message included below. I've attempted the suggested fixes described [here](https://stackoverflow.com/questions/31569339/importerror-no-module-named-cryptography-hazmat-backends-boxsdk-on-mac) with no success so far. I am unsure of next steps to resolve this error, any help is appreciated.

```
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 5, in <module>
    from superset.cli.main import superset
  File "/usr/local/lib/python3.8/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/usr/local/lib/python3.8/site-packages/superset/app.py", line 23, in <module>
    from superset.initialization import SupersetAppInitializer
  File "/usr/local/lib/python3.8/site-packages/superset/initialization/__init__.py", line 33, in <module>
    from superset.extensions import (
  File "/usr/local/lib/python3.8/site-packages/superset/extensions/__init__.py", line 32, in <module>
    from superset.utils.cache_manager import CacheManager
  File "/usr/local/lib/python3.8/site-packages/superset/utils/cache_manager.py", line 24, in <module>
    from superset.utils.core import DatasourceType
  File "/usr/local/lib/python3.8/site-packages/superset/utils/core.py", line 75, in <module>
    from cryptography.hazmat.backends.openssl.x509 import _Certificate
ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.x509'
```

**Comment by bengen343** [comment]
Howdy @lgingerich, the paths that it is looking for the packages in appear to be those of your base, local Python environment. Are you sure that you followed the instructions preceding this step to properly deploy the development container and that you're executing the `superset db upgrade` command from inside the development container environment?

**Comment by lgingerich** [comment]
Hello! It seems that this is a known issue with Superset >= 2.0.0 which I did not realize before opening this issue. It is discussed [here](https://github.com/apache/superset/issues/22571). To resolve this issue, I added the following lines to `requirements.txt`.
```
cryptography==3.4.7
WTForms==2.3.0
```
